server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
      init:
        mode: always
  jpa:
    hibernate:
      ddl-auto: validate # Controls schema generation (e.g., create, update, validate, none)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"