server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate # Controls schema generation (e.g., create, update, validate, none)
    sql:
      init:
        mode: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"